import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import { ReactNode } from 'react';
import { Database } from '../../../../packages/supabase/database.types';
import Header from './_components/Header';
import Main from './_components/Main';
import Navigation from './_components/Navigation';
import './globals.css';
import { Figtree } from 'next/font/google';

const figtree = Figtree({
  subsets: ['latin'],
});

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default async function RootLayout(props: RootLayoutProps) {
  const { children } = props;
  const supabase = createServerComponentClient<Database>({
    cookies,
  });
  const {
    data: { session },
  } = await supabase.auth.getSession();

  const isAuthenticated = Boolean(session);

  return (
    <html lang="en">
      <body className={figtree.className}>
        <Header>
          <Navigation isAuthenticated={isAuthenticated} />
        </Header>
        <Main>{children}</Main>
      </body>
    </html>
  );
}
